### ISSUE TITLE
Module removes Cartographer's Tools from built-in tool list.

### ISSUE THREAD

**Issue by ctbritt** [etoy22/elkan5e#183]
Not sure why, but with Elkan5e enabled, Cartographer's Tools are listed as just "cartographer"

![CleanShot 2024-07-22 at 11 57 25](https://github.com/user-attachments/assets/67e79073-f2ed-4e32-b172-d26a19b89d86)

![CleanShot 2024-07-22 at 11 57 52](https://github.com/user-attachments/assets/3f7100a5-591c-44da-bf02-5932f8be63d3)

**Comment by nevilspealer** [comment]
This is intentional. The Elkan 5e module modifies the tools list slightly, and Cartography tools are folded into one of the functions of Navigation Tools.

If you made a new character, you wouldn't be able to select Cartography, but an older character that still has the tools may have a tool or tool proficiency that looks like this. You could fix this by adding Navigation Tools and the Navigation Tools proficiency.

We're looking into making this a toggleable feature for users who want to play without this change.
